In [11]:
import pandas as pd
import numpy as np

In [12]:
# load training data
tfeat = pd.read_csv(r'../data/train_feautures.csv')
ttarget = pd.read_csv(r'../data/train_targets.csv')


In [40]:
tfeat.head()

dteday      temp  yr_0  yr_1  mnth_1  mnth_2  mnth_3  mnth_4  mnth_5  \
0  2011-01-01 -1.334648     1     0       1       0       0       0       0   
1  2011-01-01 -1.438516     1     0       1       0       0       0       0   
2  2011-01-01 -1.438516     1     0       1       0       0       0       0   
3  2011-01-01 -1.334648     1     0       1       0       0       0       0   
4  2011-01-01 -1.334648     1     0       1       0       0       0       0   

   mnth_6  ...  weathersit_4  windspeed1  hum1_0  hum1_1  hum1_2  hum1_3  \
0       0  ...             0           0       0       0       0       1   
1       0  ...             0           0       0       0       0       1   
2       0  ...             0           0       0       0       0       1   
3       0  ...             0           0       0       0       1       0   
4       0  ...             0           0       0       0       1       0   

   windspeed1_0  windspeed1_1  windspeed1_2  windspeed1_3  
0             1             0             0             0  
1             1             0             0             0  
2             1             0             0             0  
3             1             0             0             0  
4             1             0             0             0  

[5 rows x 29 columns]

In [42]:
tfeat=tfeat[[col for col in tfeat.columns if col!='dteday']]

In [43]:
tfeat.head()

temp  yr_0  yr_1  mnth_1  mnth_2  mnth_3  mnth_4  mnth_5  mnth_6  \
0 -1.334648     1     0       1       0       0       0       0       0   
1 -1.438516     1     0       1       0       0       0       0       0   
2 -1.438516     1     0       1       0       0       0       0       0   
3 -1.334648     1     0       1       0       0       0       0       0   
4 -1.334648     1     0       1       0       0       0       0       0   

   mnth_7  ...  weathersit_4  windspeed1  hum1_0  hum1_1  hum1_2  hum1_3  \
0       0  ...             0           0       0       0       0       1   
1       0  ...             0           0       0       0       0       1   
2       0  ...             0           0       0       0       0       1   
3       0  ...             0           0       0       0       1       0   
4       0  ...             0           0       0       0       1       0   

   windspeed1_0  windspeed1_1  windspeed1_2  windspeed1_3  
0             1             0             0             0  
1             1             0             0             0  
2             1             0             0             0  
3             1             0             0             0  
4             1             0             0             0  

[5 rows x 28 columns]

In [14]:
ttarget.head()

cnt    casual  registered
0 -0.956339 -0.662755   -0.930189
1 -0.824022 -0.561343   -0.804655
2 -0.868128 -0.622190   -0.837690
3 -0.972879 -0.662755   -0.950010
4 -1.039037 -0.723603   -1.009474

In [68]:
# forward pass parameters
input_nodes = tfeat.shape[1]
print(input_nodes)
hidden_nodes = 16
output_nodes = 1
learning_rate = 0.1

28


In [69]:
# weights
# create a matrix with the number of rows equal to input size and number of columns equal to hidden nodes
weights_input_to_hidden = np.random.normal(0.0, input_nodes**-0.5, 
                                       (input_nodes, hidden_nodes))

In [71]:
weights_input_to_hidden.shape

(28, 16)

In [48]:
# weights to ouput
weights_hidden_to_output = np.random.normal(0.0, input_nodes**-0.5, 
                                       (hidden_nodes, output_nodes))

In [49]:
weights_hidden_to_output

array([[-0.09283421],
       [ 0.09173032]])

In [50]:
#sigmoid activation function
activation_function = lambda x : 1/(1+np.exp(-x)) 

In [56]:
# input to hidden layer = X.weight_input_to_hidden : nX29.29X2 = nX2
input_to_hidden_layer =np.dot(tfeat.values,weights_input_to_hidden)
hidden_layer_after_activation = activation_function(input_to_hidden_layer)

In [52]:
tfeat.values.shape

(15435, 28)

In [57]:
input_to_hidden_layer.shape,hidden_layer_after_activation.shape

((15435, 2), (15435, 2))

In [60]:
input_to_hidden_layer[10],hidden_layer_after_activation[10]

(array([ 0.67737243, -0.10785797]), array([0.663152  , 0.47306162]))

In [61]:
# hidden layer to output layer nx2.2X1 = nx1
hidden_layer_to_output = np.dot(hidden_layer_after_activation,weights_hidden_to_output)


In [62]:
hidden_layer_to_output

array([[-0.00358171],
       [-0.00340957],
       [-0.00340957],
       ...,
       [-0.00879338],
       [-0.00879338],
       [ 0.00629096]])

In [63]:
def forward_pass(X,weights_input_to_hidden_layer,weights_hidden_to_output):
    input_to_hidden_layer = np.dot(X,weights_input_to_hidden_layer)
    hidden_layer_activated = activation_function(input_to_hidden_layer)
    hidden_layer_to_output = np.dot(hidden_layer_activated,weights_hidden_to_output)
    return hidden_layer_to_output,hidden_layer_activated

In [66]:
output,hidden_layer_activated = forward_pass(tfeat.values,weights_input_to_hidden,weights_hidden_to_output)

In [67]:
output.shape,hidden_layer_activated.shape

((15435, 1), (15435, 2))